In [30]:
from scipy import stats
import numpy as np

In [5]:
r = np.random.randint(0,10)
print(r)

5


In [6]:
x = [np.random.randint(0,10) for i in range(1000)]
print(x)

[6, 2, 9, 2, 1, 5, 2, 4, 9, 7, 1, 0, 2, 2, 5, 5, 0, 5, 9, 3, 8, 3, 2, 8, 8, 8, 9, 6, 3, 9, 4, 3, 4, 5, 9, 0, 7, 5, 8, 1, 3, 9, 5, 7, 5, 4, 2, 8, 2, 5, 0, 6, 1, 2, 2, 1, 9, 1, 5, 8, 8, 0, 6, 0, 2, 0, 6, 3, 6, 8, 2, 8, 3, 3, 1, 3, 9, 0, 4, 1, 5, 4, 8, 6, 9, 0, 9, 4, 3, 3, 0, 9, 1, 4, 4, 2, 0, 3, 8, 2, 6, 1, 8, 4, 9, 1, 3, 6, 4, 6, 7, 7, 5, 7, 5, 3, 1, 5, 4, 1, 3, 3, 4, 2, 1, 4, 3, 7, 5, 2, 7, 1, 7, 6, 7, 0, 0, 5, 4, 5, 9, 9, 0, 3, 3, 2, 7, 8, 1, 1, 3, 5, 8, 2, 3, 0, 5, 1, 1, 0, 5, 0, 5, 4, 9, 8, 5, 5, 5, 2, 0, 1, 6, 7, 9, 9, 4, 2, 2, 3, 1, 1, 5, 0, 6, 0, 2, 4, 0, 9, 5, 6, 0, 8, 6, 6, 7, 5, 8, 2, 5, 8, 0, 4, 0, 6, 1, 4, 2, 3, 3, 2, 0, 8, 2, 6, 0, 3, 8, 5, 7, 3, 0, 7, 9, 2, 9, 1, 8, 7, 3, 3, 5, 2, 5, 4, 6, 9, 5, 6, 7, 2, 0, 3, 1, 9, 7, 1, 5, 5, 2, 0, 6, 1, 8, 4, 5, 8, 5, 1, 6, 2, 6, 4, 5, 7, 5, 7, 6, 2, 2, 7, 6, 0, 0, 0, 8, 2, 0, 2, 1, 6, 0, 7, 7, 8, 4, 0, 1, 5, 2, 6, 4, 8, 8, 7, 8, 3, 9, 9, 6, 0, 3, 3, 6, 4, 2, 6, 1, 4, 7, 5, 8, 6, 4, 3, 0, 0, 5, 7, 3, 6, 2, 3, 2, 4, 1, 4, 5, 9, 4, 7, 5, 

In [9]:
average = np.mean(x)
print(average)
median = np.median(x)
print(median)

4.396
4.0


In [17]:
print(x.count(1))

93


In [18]:
mode = stats.mode(x)
print(mode)
print(type(mode))

ModeResult(mode=array([2]), count=array([116]))
<class 'scipy.stats.stats.ModeResult'>


In [16]:
print(mode[0])
print(mode[1])

[2]
[116]


In [19]:
from scipy import special

In [25]:
e = special.exp10(1)
print(e)
print(type(e))

10.0
<class 'numpy.float64'>


In [26]:
e1= special.exp2(4)
print(e1)

16.0


In [29]:
print(special.sindg(90))

1.0


In [31]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [33]:
a = np.array((1,2,3,4))
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [34]:
#0-D
a0 = np.array(23)
print(a0)

23


In [35]:
#1-D
a1 = np.array([1,2,3,4,5,6,7,8,9])
print(a1)

[1 2 3 4 5 6 7 8 9]


In [37]:
#2-D
a2 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [39]:
#3-D
a3 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [43]:
#Checking Dimension

print(a3.ndim)

3


In [45]:
ab = np.array([1,2,3,4,5], ndmin = 2)
print(ab)
print(ab.ndim)

[[1 2 3 4 5]]
2


In [49]:
print(a3.shape)

(2, 2, 3)


In [50]:
#slicing
print(a1)

[1 2 3 4 5 6 7 8 9]


In [53]:
print(a1[2:])

[3 4 5 6 7 8 9]


In [56]:
print(a1[2:6:2])

[3 5]


In [57]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [58]:
for i in range(len(a2)):
    print(a2[i,2])

3
7


In [59]:
print(a2.dtype)

int32


In [62]:
arr = np.array([1,2],dtype=complex)
print(arr)
print(arr.dtype)

[1.+0.j 2.+0.j]
complex128


In [64]:
zeroa = np.zeros(shape= (3,2))
print(zeroa)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [67]:
onea = np.ones((3,2,2))
print(onea)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [86]:
A = np.arange(12)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [90]:
B= A.reshape(4,-1)
print(B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [91]:
array = np.arange(15).reshape(3,5)
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [92]:
print(array.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [93]:
print(array.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [96]:
randoma =np.random.rand(10)
print(randoma)

[0.1370879  0.729178   0.81620162 0.98807037 0.10912563 0.78131475
 0.36296238 0.39294986 0.19792416 0.48799573]


In [99]:
print(randoma.reshape(5,-1))

[[0.1370879  0.729178  ]
 [0.81620162 0.98807037]
 [0.10912563 0.78131475]
 [0.36296238 0.39294986]
 [0.19792416 0.48799573]]


In [6]:
import numpy as np
A = np.array([[3,6,7],[5,3,0]])
B= np.array([[1,1],[2,1],[3,-3]])


In [8]:
#r1Xc1 r2Xc2 --> c1==r2
c= B.dot(A)
print(c)

[[ 8  9  7]
 [11 15 14]
 [-6  9 21]]


In [9]:
A= np.array([[2,4],[5,6]])
B = np.array([[9,3],[7,8]])


In [10]:
C=A+B
print(C)

[[11  7]
 [12 14]]


In [15]:
print(A)
print(A.transpose())
print(A.T)

[[2 4]
 [5 6]]
[[2 5]
 [4 6]]
[[2 5]
 [4 6]]
